
dataset_root: "datasets/RAF-DB"

images_dir: "datasets/RAF-DB/DATASET"

openface_output_dir: "datasets/RAF-DB/OpenFace_AU_Outputs"

au_feature_csv: "datasets/RAF-DB/aus_features.csv"

au_sources:
  - "datasets/RAF-DB/aus_features_pose_norm.csv"
  - "datasets/RAF-DB/aus_features_original.csv"


splits_dir: "splits"


train_split_csv: "splits/rafdb_train.csv"
val_split_csv: "splits/rafdb_val.csv"

train_split_with_aus: "splits/rafdb_train_with_aus.csv"
val_split_with_aus: "splits/rafdb_val_with_aus.csv"


cache_dir: "cache"
logs_dir: "logs/aus_processing"
