# ===========================================
# CONFIG FILE FOR AU FEATURE MANAGEMENT
# ===========================================

# Root dataset directory (RAF-DB base)
image_directory:
  train_images_dir: "datasets/RAF-DB/DATASET/train"
  test_images_dir:  "datasets/RAF-DB/DATASET/test"

au_splits:
  aus_training_split : 'splits/aus_raf_train_1.csv'
  aus_validation_split : 'splits/aus_raf_test_1.csv'

saved_models_dir: "Saved_Models"
au_mae_model_path:
  pretrained_au_mae_weights: "Saved_Models/au_mae_pretrained_best.pth"
  pretrained_au_mae_model: "Saved_Models/au_mae_pretrained_full.pt"
# If you have multiple AU sources (e.g., cropped, frontal, etc.)
# you can list them here for experimentation


# -------------------------------
# Optional backup or cache paths
# -------------------------------
cache_dir: "cache"
logs_dir: "logs/aus_processing"
